sess: |
  [default]
  FileStorePath=fsp
  SocketConnectHost=localhost
  SocketConnectPort=9876
  HeartBtInt=30
  ReconnectInterval=5
  ConnectionType=initiator
  StartTime=00:00:00
  EndTime=00:00:00
  
  [session]
  BeginString=FIX.4.2
  SenderCompID=BANZAI
  TargetCompID=EXEC
  ResetOnLogon=Y
  DataDictionary=FIX42.xml
  
